version: '3.7'
services: 
    web:
      container_name: web
      image: nginx
      volumes:
      - ./public:/usr/share/nginx/html
      - ./templates:/etc/nginx/templates
      ports:
      - "80:80"
      environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80